### ISSUE TITLE
Response JSON for `/search` and `/collections/{collectionsid/items` does not match

### ISSUE THREAD

**Issue by Nobralyra** [SDFIdk/skraafoto_stac_public#34]
GET https://api.dataforsyningen.dk/skraafotoapi_test/search?bbox=15,55,16,56

Body fremgår som null

![image](https://user-images.githubusercontent.com/48592380/169776661-9699f635-5499-4499-b243-35ef5a6be5fc.png)

GET https://api.dataforsyningen.dk/skraafotoapi_test/collections/skraafotos2019/items?bbox=15,55,16,56

Body fremgår som false

![image](https://user-images.githubusercontent.com/48592380/169776965-a662a6e7-78c6-415e-97ac-98e973fb5f3a.png)

**Comment by AsgerPetersen** [comment]
`body` bruges til at angive den http request body, som skal medsendes ifbm paging. Se https://github.com/radiantearth/stac-api-spec/tree/62003db924fe6630545400a41b62fe052d65b8ff/item-search#pagination

Den rigtige løsning er at fjerne `link.body` helt ved `GET` requests.
